platform :ios, '12.0'

target 'ConvivaReporter' do
  # Use the ConvivaConnector that is locally defined in the parent directory
  pod 'THEOplayer-Connector-Conviva', :path => '../../Conviva'

  # When you want to use a custom THEOplayerSDK build:
  #  - place your build at '../../../Helpers/TheoPod/Frameworks/THEOplayerSDK.xcframework'
  #  - uncomment the following line
  # pod 'THEOplayerSDK-basic', :path => '../../../Helpers/TheoPod'
end