platform :ios, '12.0'

target 'SideloadedTextTracksExample' do
  # Use the ComscoreConnector that is locally defined in the parent directory
  pod 'THEOplayer-Connector-SideloadedSubtitle', :path => '../../../'

  # When you want to use a custom THEOplayerSDK build:
  #  - place your build at '../../../Helpers/TheoPod/Frameworks/THEOplayerSDK.xcframework'
  #  - uncomment the following line
  # pod 'THEOplayerSDK-core', :path => '../../../Helpers/TheoPod'

end
