platform :ios, '13.0'

target 'GemiusReporter' do
  # Use the AdscriptConnector that is locally defined in the parent directory
  pod 'THEOplayer-Connector-Gemius', :path => '../../../'
  pod 'THEOplayer-Integration-GoogleIMA', '~> 9'
  pod 'GemiusSDK', :path => 'Frameworks/'

  # When you want to use a custom THEOplayerSDK build:
  #  - place your build at '../../../Helpers/TheoPod/Frameworks/THEOplayerSDK.xcframework'
  #  - uncomment the following line
  # pod 'THEOplayerSDK-core', :path => '../../../Helpers/TheoPod'

end